version: "3.5"
services:
  shop:
    container_name: shop
    image: webdevops/php-apache:8.0
    volumes:
      - "./:/app"
    environment:
      WEB_DOCUMENT_ROOT: /app/public/
    depends_on:
      - db
    networks:
      cloud_net:
        ipv4_address: 172.21.3.10

  db:
    container_name: db
    image: mysql
    volumes:
      - "./mysql/shop:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: shop
      MYSQL_USER: shop
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      cloud_net:
        ipv4_address: 172.21.3.20

networks:
  cloud_net:
    name: dev_net
    ipam:
      driver: default
      config:
        - subnet: 172.21.3.0/24
